### PR TITLE
add: example-ui

### LINKED ISSUE #2: Port over example-ui
Example-ui should live in this repo as well. This can be found in the old `nomad-monorepo` (now deprecated)

### PR DESCRIPTION
**Pull request by ErinHales**
Closes #2

### CODE REVIEW

**Comment by Imti** [comment]
@ErinHales Can we name it `bridge-gui` or something? Trying to avoid having `examples/example-blah` in the folder structure

**Comment by Imti** [comment]
Also, mind removing the `package-lock.json` and running `yarn install` to commit the `yarn.lock` instead? Trying to move all new code to use `yarn` instead for dependency management.

**Comment by ErinHales** [comment]
Absolutely, made those changes!

**Review by Imti — APPROVED** [review]
🔖

**Pull request merged**
